#request constants
#int8 FOO=1
#int8 BAR=2
#request fields
int32[] input
#int32 y
#another_pkg/AnotherMessage msg
---
#response constants
#uint32 SECRET=123456
#response fields
#another_pkg/YetAnotherMessage val
#CustomMessageDefinedInThisPackage value
# string comment
int32 result